// Импорт файлов в main.js
import './homeworks/homework-4.js'
import './homeworks/homework-5.js'
import './homeworks/homework-6.js'
import './homeworks/homework-7.js'
import './homeworks/homework-8.js'
import './homeworks/homework-9.js'
import './homeworks/homework-10/homework-10.js'
import './homeworks/homework-10/modal.js'
import './homeworks/homework-10/form.js'
