// Импорт файлов в main.js
import './homeworks/homework-4.js'
import './homeworks/homework-5.js'
import './homeworks/homework-6.js'
import './homeworks/homework-7.js'
import './homeworks/homework-8.js'
import './homeworks/homework-10/homework-10.js'
import './homeworks/homework-10/Form.js'
import './homeworks/homework-11/homework-11.js'
import './homeworks/homework-12/Modal.js'